---

- name: Install specific version of nginx server
  apt:
    name: nginx={{ nginx_version }}
  notify:
    - systemd enable
  when: ansible_os_family == 'Debian'

- name: Install our hello world onto the nginx server
  template:
    src: hello-world-welcome.j2
    dest: /var/www/html/index.nginx-debian.html
    owner: www-data
    group: www-data
    mode: 0644
  notify:
  - reload nginx